langfuse:
  salt:
    secretKeyRef:
      name: my-secretenv
      key: langfuse-salt
  encryptionKey:
    secretKeyRef:
      name: my-secretenv
      key: langfuse-encryption-key
  env:
    NEXTAUTH_URL: "https://langfuse.isskar-hub.com"
    # AUTH_AUTH0_CLIENT_ID: "<CLIENT_ID>"
    # AUTH_AUTH0_CLIENT_SECRET: "<CLIENT_SECRET>"
    # AUTH_AUTH0_ISSUER: "https://<TENANT>.eu.auth0.com"
    AUTH_AUTH0_ALLOW_ACCOUNT_LINKING: "true"
    AUTH_DOMAINS_WITH_SSO_ENFORCEMENT: "isskar-hub.com"

postgresql:
  auth:
    existingSecret: my-secretenv
    secretKeys:
      adminPasswordKey: langfuse-postgres-password
      userPasswordKey: langfuse-postgres-password

clickhouse:
  enabled: false

valkey:
  enabled: false

minio:
  enabled: false