apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}-web
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    {{- with .Values.langfuse.web.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.langfuse.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.langfuse.web.service.type }}
  ports:
    - port: {{ .Values.langfuse.web.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.langfuse.web.service.nodePort }}
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
    app: web
