{{- if .Values.langfuse.ingress.enabled -}}
{{- if and .Values.langfuse.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.langfuse.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.langfuse.ingress.annotations "kubernetes.io/ingress.class" .Values.langfuse.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "langfuse.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    {{- with .Values.langfuse.ingress.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.langfuse.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.langfuse.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.langfuse.ingress.className }}
  {{- end }}
  {{- if .Values.langfuse.ingress.tls.enabled }}
  tls:
    {{- if .Values.langfuse.ingress.tls.enabled }}
    - hosts:
        {{- range .Values.langfuse.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Values.langfuse.ingress.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.langfuse.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "langfuse.fullname" $ }}-web
                port:
                  name: http
              {{- else }}
              serviceName: {{ include "langfuse.fullname" $ }}-web
              servicePort: http
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
