{{- if .Values.langfuse.nextauth.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.nextauthSecretName" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  nextauth-secret: {{ .Values.langfuse.nextauth.secret | toString | b64enc }}
{{- end }}