{{- if (not .Values.langfuse.salt.valueFrom) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.saltSecretName" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.langfuse.salt.valueFrom }}
  nextauth-secret: {{ .Values.langfuse.salt.value | toString | b64enc }}
  {{- end }}
{{- end }}
